eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/v1/department/**
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/employee/**
        - id: ORGANISATION-SERVICE
          uri: lb://ORGANISATION-SERVICE
          predicates:
            - Path=/api/v1/organisation/**
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

#logging:
#  level:
#    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG

